# Generated by Django 5.1.6 on 2025-02-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mri_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mriimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='mriimage',
            name='disease_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mriimage',
            name='prediction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
